title: "UWSCR入門"
summary: "UWSCRは現在開発中のUWSC互換スクリプト実行ツールです。\nUWSCからの変更点や新しく追加された機能を中心に解説していきます。\nすでにある程度UWSCが扱える方が対象です。\n\n※ 開発中のため仕様変更に伴い記事の内容も修正される可能性があります。\n\nhttps://github.com/stuncloud/UWSCR"
topics: ["uwsc", "uwscr"]
published: false
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - setup
  - variables
  - types
  - new-feature-single-quoted-string-literal
  - new-feature-expand-identifier
  - new-feature-array-literal
  - new-feature-hash-endhash
  - new-feature-enum-endenum
