title: "UWSCR入門"
summary: |-
  UWSCRは現在開発中のUWSC互換スクリプト実行ツールです。
  https://github.com/stuncloud/UWSCR
  UWSCからの変更点や新しく追加された機能を中心に解説していきます。
  すでにある程度UWSCが扱える方が対象です。

  ※ 開発中のため仕様変更に伴い記事の内容も修正される可能性があります。
  ※ 有料記事ですがすべてのチャプターを無料でお読みいただけます
topics:
  - "uwscr"
  - "uwsc"
published: false
price: 1000 # 有料の場合200〜5000
toc_depth: 1
# 本に含めるチャプターを順番に並べましょう
chapters:
  - setup
  - variables
  - types
  - new-feature-single-quoted-string-literal
  - new-feature-expand-identifier
  - new-feature-array-literal
  - new-feature-hash-endhash
  - new-feature-enum-endenum
